### ISSUE TITLE
updated map via topojson-map-generator

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#85]
I've used [topojson-map-generator](https://github.com/melalj/topojson-map-generator) to create a new JSON map.  I did ``./generate.sh  -c`` and then ``./generate.sh  -l -a`` and it gave me ``ne_110m_admin_0_countries_lakes_wo_antarctica.json`` as expected:
[ne_110m_admin_0_countries_lakes_wo_antarctica.json.zip](https://github.com/Packet-Clearing-House/maptable/files/2200371/ne_110m_admin_0_countries_lakes_wo_antarctica.json.zip)

However, when I try and use this file with maptable, none of the countries work (choropleth map fails to highlight).  Looking at the resulting JSON linked above, it seems different than the [JSON maptable has used](https://github.com/Packet-Clearing-House/maptable/blob/master/examples/ne_110m_admin_0_countries.json).  Maybe something changed upstream?  Maybe Maptable needs to be updated?

While we're in here, how do get a JSON file with out Somaliland?  I found an [old comment about it](https://www.naturalearthdata.com/blog/natural-earth-version-1-4-release-notes/#comment-978), but I don't quite follow the advice.

Thanks!

**Comment by melalj** [comment]
It seems that the generated JSON doesn't include properties of every country (as the one used for maptable)

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - yup, that's what I thought I saw when visually comparing them.  

So is this a problem with topojson-map-generator or with the source files from Natural Earth?

As well, thoughts on my Somaliland question?

**Comment by melalj** [comment]
@Ths2-9Y-LqJt6 What I understood from that comment is that Somaliland is considered as a admin-1 region instead of a admin-0 (which is Somalia) (maybe California would be admin-1 for the US).

The country properties are added on this line: https://github.com/melalj/topojson-map-generator/blob/master/generate.sh#L134

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - thanks for the reply!

However, I don't feel any closer to an answer :(  I see that line 134 is where the country properties are added. I agree that Somaliland is considered as a admin-1.  

I still can't generate a new JSON that has the country properties.  MapTable is shipping with admin-0 JSON that still has Somaliland in it.

**Comment by melalj** [comment]
@Ths2-9Y-LqJt6 Alright, I ran the script and found out where was the problem, just updated the repo with a more complete README 😉
https://github.com/melalj/topojson-map-generator

Let me know what you think

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - thanks!  

This looks to work in that I can get working JSON out of it, but there's been a [minor regression](https://github.com/melalj/topojson-map-generator/commit/334c8732570db6dc146d1d014f11a68d4b6214a4#r29805598). As well, my resulting file "maps/ne_50m_admin_0_countries_lakes_wo_antarctica.json" (note the "admin_0") still has Somaliland.

**Comment by melalj** [comment]
Alright, I found out a way to downcase the properties. It should work now :)

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - Thanks, looks good! 

What about Somaliland?

**Comment by Ths2-9Y-LqJt6** [comment]
Hmm...I don't think this approach is going to work for two reasons:
 1. When you do this it just wipes Somaliland off the map.  We actually want to join Somaliland and Somalia so that their both Somalia. Skipping country just makes it a white space
 1. France, Norway as well as Somaliland disappeared ;)

**Comment by melalj** [comment]
Understood, Found out a thread that helped to tweak the script: https://github.com/markmarkoh/datamaps/issues/76

Tested the map and it worked (see somliland and western sahara)
The issue is that these hight admin area, lost their name and iso_code...

<img width="1192" alt="screenshot 2018-07-25 23 58 11" src="https://user-images.githubusercontent.com/3869766/43232058-09dc0aa6-9067-11e8-88af-db3324d896ad.png">

I updated the code on this PR: https://github.com/melalj/topojson-map-generator/pull/4

**Comment by Ths2-9Y-LqJt6** [comment]
merged somilia looks good!  thanks.  I'll give the ``topojson-merge`` branch a try and report back in a bit.

**Comment by Ths2-9Y-LqJt6** [comment]
Ok - the 110m JSON looks good! France, and Norway are there, Somilia is all big ;)  The 50m on the other hand, still has all three problems.

**Comment by Ths2-9Y-LqJt6** [comment]
So after we chatted on IM yesterday, you published the [demo](https://github.com/Packet-Clearing-House/maptable/tree/ixpdir-topojson/examples/ixpdir) on the branch on maptable.  Things are a lot better! Somalia is merged, norway and France are there.  However, I'm still seeing France wrong in the [50m JSON](https://github.com/Packet-Clearing-House/maptable/blob/ixpdir-topojson/examples/ixpdir/countries.topo.json):

```json
{"adm0_a3":"FRA","iso_a2":"-99","iso_a3":"-99","continent":"Europe","name":"France"}
```
Should be:
```json
{"iso_a2":"FR","iso_a3":"FRA","continent":"Europe","name":"France"}
```
While we're in there, we should remove ``"adm0_a3":"FRA",`` as it's a duplicate of the ``"iso_a3":"FRA"`` data and we should try to keep the JSON as small as possible. Unless it has another use I don't know about and we should keep it?  At a minimum, we should have a flag to add/remove it in ``generate.sh``.

As well, Australia is severely truncated in that same 50m JSON. The shape is there, but the entry is incomplete:

```json
{"adm0_a3":"AUS"}
```

**Comment by Ths2-9Y-LqJt6** [comment]
Interesting!  The [old 50m json is 745k](https://web.archive.org/web/20180425044215/https://www.pch.net/assets/data/countries.topo.json?2018-03-15) and the [new one is 592k](https://www.pch.net/assets/data/countries.topo.json?2018-07-26)!

**Comment by melalj** [comment]
When we merged the dataset using the ADM0_A3, topojson-merge skips the properties from the two merged lands. ISO_A3 and ADM0_A3 had different usage before the merge, and now they are duplicated indeed.
At the moment, I don't see an quick/easy solution to fix, so let's make the edits manually - since the code is open, any external help would be welcome :)

Closing this ticket for now 😉
